#!/usr/bin/python3

import os, sys, subprocess
branch = sys.argv[1]
index = int(sys.argv[2])

# git checkout branch
os.system("git checkout " + branch)

# collect full list of commits
git_log = "\n"+str(subprocess.check_output(["git", "log"]), "utf-8")
git_commits = git_log.split("\ncommit ")[1:]
git_commits = [commit.split("\n")[0] for commit in git_commits]

# check out index'th commit
os.system("git checkout " + git_commits[::-1][index])
